-- Run this once in Supabase SQL Editor before deploying the Vercel frontend.
-- The browser uses only the anon key; service-role keys must never be shipped.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null,
  email text not null,
  phone text,
  role text not null default 'customer',
  district text,
  address text,
  id_number text,
  service_areas text[] not null default '{}',
  kvkk_consent boolean not null default false,
  kvkk_consent_at timestamptz,
  kvkk_consent_version text,
  is_approved boolean not null default false,
  is_blocked boolean not null default false,
  created_at timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, name, email, role)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'name', split_part(coalesce(new.email, 'Kullanıcı'), '@', 1), 'Kullanıcı'),
    coalesce(new.email, ''),
    coalesce(new.raw_user_meta_data->>'role', 'customer')
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

create table if not exists public.ustas (
  id bigint generated by default as identity primary key,
  profile_id uuid not null unique references public.profiles(id) on delete cascade,
  name text not null,
  phone text,
  specialty text not null,
  specialties text[] not null default '{}',
  category_id text not null default 'diger',
  rating numeric not null default 4.5,
  review_count integer not null default 0,
  experience integer not null default 0,
  bio text,
  lat double precision,
  lng double precision,
  is_online boolean not null default false,
  verified boolean not null default false,
  service_areas text[] not null default '{}',
  created_at timestamptz not null default now()
);

create table if not exists public.usta_locations (
  usta_id bigint primary key references public.ustas(id) on delete cascade,
  usta_name text not null,
  specialty text not null,
  category_id text not null,
  lat double precision not null,
  lng double precision not null,
  heading double precision,
  is_online text not null default 'true',
  updated_at timestamptz not null default now()
);

create table if not exists public.requests (
  id bigint generated by default as identity primary key,
  owner_id uuid references public.profiles(id) on delete set null,
  user_name text not null default 'Kullanıcı',
  category_id text not null,
  category_name text not null,
  title text not null,
  description text,
  priority text not null default 'Bugün',
  time_range text,
  semt text not null,
  mahalle text not null,
  sokak text,
  status text not null default 'Beklemede',
  assigned_usta_id bigint references public.ustas(id) on delete set null,
  customer_latitude double precision,
  customer_longitude double precision,
  artisan_latitude double precision,
  artisan_longitude double precision,
  tracking_status text not null default 'Beklemede',
  photos text[] not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Request lifecycle additions. These are intentionally additive so existing
-- requests remain readable after this feature is enabled.
alter table public.requests add column if not exists delivery_status text;
alter table public.requests add column if not exists cancellation_reason text;
alter table public.requests add column if not exists unreachable_reason text;
alter table public.requests add column if not exists rating_protected boolean not null default false;

create table if not exists public.request_events (
  id bigint generated by default as identity primary key,
  request_id bigint not null references public.requests(id) on delete cascade,
  actor_id uuid not null references public.profiles(id) on delete cascade,
  action text not null,
  reason text,
  created_at timestamptz not null default now()
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  recipient_id uuid not null references public.profiles(id) on delete cascade,
  request_id bigint references public.requests(id) on delete cascade,
  title text not null,
  message text not null,
  type text not null,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.support_messages (
  id bigint generated by default as identity primary key,
  session_id text not null,
  sender_name text not null,
  email text,
  message text not null,
  is_agent boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  usta_id bigint not null references public.ustas(id) on delete cascade,
  request_id bigint references public.requests(id) on delete set null,
  rating integer not null check (rating between 1 and 5),
  comment text,
  reviewer_name text not null,
  created_at timestamptz not null default now(),
  unique (usta_id, request_id)
);

alter table public.profiles enable row level security;
alter table public.ustas enable row level security;
alter table public.usta_locations enable row level security;
alter table public.requests enable row level security;
alter table public.support_messages enable row level security;
alter table public.reviews enable row level security;
alter table public.request_events enable row level security;
alter table public.notifications enable row level security;

create or replace function public.is_admin() returns boolean
language sql stable security definer set search_path = public
as $$
  select exists(
    select 1
    from public.profiles
    where id = auth.uid()
      and not is_blocked
      and (role = 'admin' or lower(email) = 'bekirsevcan1@gmail.com')
  );
$$;

create policy "profiles self or admin read" on public.profiles for select to authenticated
using (id = auth.uid() or public.is_admin());
create policy "profiles self insert" on public.profiles for insert to authenticated
with check (id = auth.uid());
create policy "profiles self update or admin" on public.profiles for update to authenticated
using (id = auth.uid() or public.is_admin())
with check (id = auth.uid() or public.is_admin());
create policy "verified providers public read" on public.ustas for select to anon, authenticated
using (verified = true or profile_id = auth.uid() or public.is_admin());
create policy "provider self insert" on public.ustas for insert to authenticated
with check (profile_id = auth.uid());
create policy "provider self update or admin" on public.ustas for update to authenticated
using (profile_id = auth.uid() or public.is_admin())
with check (profile_id = auth.uid() or public.is_admin());
create policy "public online locations read" on public.usta_locations for select to anon, authenticated
using (is_online = 'true' or public.is_admin());
create policy "provider own location write" on public.usta_locations for insert to authenticated
with check (exists(select 1 from public.ustas where id = usta_id and profile_id = auth.uid()));
create policy "provider own location update" on public.usta_locations for update to authenticated
using (exists(select 1 from public.ustas where id = usta_id and profile_id = auth.uid()) or public.is_admin());
create policy "request owner or admin read" on public.requests for select to authenticated
using (owner_id = auth.uid() or public.is_admin());
create policy "request owner insert" on public.requests for insert to authenticated
with check (owner_id = auth.uid());
create policy "request owner or admin update" on public.requests for update to authenticated
using (owner_id = auth.uid() or public.is_admin());

-- Assigned providers may update lifecycle fields; the client still validates
-- the allowed action and the event actor is recorded for auditability.
create policy "assigned provider request update" on public.requests for update to authenticated
using (exists (select 1 from public.ustas where id = assigned_usta_id and profile_id = auth.uid()))
with check (exists (select 1 from public.ustas where id = assigned_usta_id and profile_id = auth.uid()));
create policy "request event actor insert" on public.request_events for insert to authenticated
with check (actor_id = auth.uid());
create policy "request owner provider event read" on public.request_events for select to authenticated
using (
  actor_id = auth.uid()
  or exists (select 1 from public.requests r where r.id = request_id and (r.owner_id = auth.uid() or public.is_admin()))
);
create policy "notification recipient read" on public.notifications for select to authenticated
using (recipient_id = auth.uid() or public.is_admin());
create policy "notification recipient update" on public.notifications for update to authenticated
using (recipient_id = auth.uid() or public.is_admin())
with check (recipient_id = auth.uid() or public.is_admin());
create policy "notification insert authenticated" on public.notifications for insert to authenticated
with check (
  exists (
    select 1 from public.requests r
    left join public.ustas u on u.id = r.assigned_usta_id
    where r.id = request_id
      and (r.owner_id = auth.uid() or u.profile_id = auth.uid() or public.is_admin())
      and (recipient_id = r.owner_id or recipient_id = u.profile_id)
  )
);
create policy "support session read" on public.support_messages for select to anon, authenticated
using (true);
create policy "support visitor insert" on public.support_messages for insert to anon, authenticated
with check (is_agent = false);
create policy "support admin reply" on public.support_messages for insert to authenticated
with check (is_agent = true and public.is_admin());

create policy "reviews public read" on public.reviews for select to anon, authenticated
using (true);
create policy "review authenticated insert" on public.reviews for insert to authenticated
with check (
  exists (
    select 1 from public.requests
    where requests.id = request_id and requests.owner_id = auth.uid()
  )
);

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'usta_locations'
  ) then
    alter publication supabase_realtime add table public.usta_locations;
  end if;
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'support_messages'
  ) then
    alter publication supabase_realtime add table public.support_messages;
  end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'requests'
  ) then
    alter publication supabase_realtime add table public.requests;
  end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'notifications'
  ) then
    alter publication supabase_realtime add table public.notifications;
  end if;
end
$$;