const colors = {
  dark: {
    background: '#121212',
    foreground: '#FFFFFF',
    card: '#1E1E1E',
    cardForeground: '#FFFFFF',
    primary: '#FF9500',        // Ana turuncu — butonlar
    primaryForeground: '#FFFFFF',
    secondary: '#2A2A2A',
    secondaryForeground: '#FFFFFF',
    muted: '#2A2A2A',
    mutedForeground: '#8E8E93',
    accent: '#00C8B3',         // Teal — aktif ikonlar, seçim
    accentForeground: '#121212',
    destructive: '#FF453A',
    destructiveForeground: '#FFFFFF',
    border: '#2C2C2C',
    input: '#1E1E1E',
    text: '#FFFFFF',
    tint: '#FF9500',
    teal: '#00C8B3',
    purple: '#BF5AF2',
    blue: '#0A84FF',
    green: '#30D158',
    orange: '#FF9500',
  },
  light: {
    background: '#121212',
    foreground: '#FFFFFF',
    card: '#1E1E1E',
    cardForeground: '#FFFFFF',
    primary: '#FF9500',
    primaryForeground: '#FFFFFF',
    secondary: '#2A2A2A',
    secondaryForeground: '#FFFFFF',
    muted: '#2A2A2A',
    mutedForeground: '#8E8E93',
    accent: '#00C8B3',
    accentForeground: '#121212',
    destructive: '#FF453A',
    destructiveForeground: '#FFFFFF',
    border: '#2C2C2C',
    input: '#1E1E1E',
    text: '#FFFFFF',
    tint: '#FF9500',
    teal: '#00C8B3',
    purple: '#BF5AF2',
    blue: '#0A84FF',
    green: '#30D158',
    orange: '#FF9500',
  },
  radius: 12,
};

export default colors;
export type ColorScheme = typeof colors.dark;
